//! native_fusion/native/stats.rs
//!
//! Demonstrates both styles of Native Fusion interop:
//!
//! 1. **Standalone BIFs** via `#[matchbox_fn]`:
//!    - fast_fib(n)        → nth Fibonacci number (iterative)
//!    - fast_factorial(n)  → n! factorial (iterative)
//!
//! 2. **Native object** via `#[matchbox_class]` + `#[matchbox_methods]`:
//!    - RunningStats — accumulates numbers pushed to it and reports
//!      count, sum, mean, min, and max.
//!      BoxLang: `s = new rust:stats.RunningStats()`
//!
//! MatchBox detects any `.rs` file inside a `native/` directory and compiles
//! it alongside the VM. `register_bifs()` and `register_classes()` are the
//! entry points called at startup.

use matchbox_vm::{
    matchbox_class, matchbox_fn, matchbox_methods,
    types::{BxNativeFunction, BxNativeObject, BxValue, BxVM},
};
use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;

// ---------------------------------------------------------------------------
// BIF: fast_fib(n) → number
// ---------------------------------------------------------------------------

/// Compute the nth Fibonacci number iteratively.
///
/// `#[matchbox_fn]` generates `fast_fib_wrapper`, which is what MatchBox
/// actually calls. The wrapper validates the argument count and converts
/// the `f64` argument automatically before calling this function.
///
/// BoxLang usage:
/// ```boxlang
/// println(fast_fib(10))   // 55
/// println(fast_fib(40))   // 102334155
/// ```
#[matchbox_fn]
pub fn fast_fib(n: f64) -> f64 {
    let n = n as u64;
    if n == 0 { return 0.0; }
    if n == 1 { return 1.0; }

    let mut a: u64 = 0;
    let mut b: u64 = 1;
    for _ in 2..=n {
        let next = a + b;
        a = b;
        b = next;
    }
    b as f64
}

// ---------------------------------------------------------------------------
// BIF: fast_factorial(n) → number
// ---------------------------------------------------------------------------

/// Compute n! (factorial) iteratively.
///
/// `#[matchbox_fn]` generates `fast_factorial_wrapper` automatically.
///
/// BoxLang usage:
/// ```boxlang
/// println(fast_factorial(10))   // 3628800
/// println(fast_factorial(20))   // 2432902008176640000
/// ```
#[matchbox_fn]
pub fn fast_factorial(n: f64) -> f64 {
    let n = n as u64;
    (1..=n).product::<u64>() as f64
}

// ---------------------------------------------------------------------------
// Native object: RunningStats
// ---------------------------------------------------------------------------

/// A stateful accumulator exposed to BoxLang as a native object.
///
/// `#[matchbox_class]` auto-implements `BxNativeObject`, delegating method
/// calls to the dispatcher generated by `#[matchbox_methods]`.
///
/// BoxLang usage:
/// ```boxlang
/// s = new rust:stats.RunningStats()
/// s.push(10)
/// s.push(20)
/// s.push(30)
/// println(s.mean())    // 20
/// println(s.min())     // 10
/// println(s.max())     // 30
/// ```
#[matchbox_class]
#[derive(Debug)]
pub struct RunningStats {
    values: Vec<f64>,
}

/// `#[matchbox_methods]` generates a `dispatch_method` router that maps
/// BoxLang method names (case-insensitive) to the Rust methods below.
/// Parameter types are coerced automatically using the same rules as
/// `#[matchbox_fn]`.
#[matchbox_methods]
impl RunningStats {
    /// Append a value to the accumulator.
    pub fn push(&mut self, value: f64) -> f64 {
        self.values.push(value);
        self.values.len() as f64
    }

    /// Number of values pushed so far.
    pub fn count(&self) -> f64 {
        self.values.len() as f64
    }

    /// Sum of all pushed values.
    pub fn sum(&self) -> f64 {
        self.values.iter().sum()
    }

    /// Arithmetic mean, or 0 if no values have been pushed.
    pub fn mean(&self) -> f64 {
        if self.values.is_empty() {
            return 0.0;
        }
        self.sum() / self.count()
    }

    /// Minimum value pushed, or 0 if empty.
    pub fn min(&self) -> f64 {
        self.values.iter().cloned().fold(f64::INFINITY, f64::min)
    }

    /// Maximum value pushed, or 0 if empty.
    pub fn max(&self) -> f64 {
        self.values.iter().cloned().fold(f64::NEG_INFINITY, f64::max)
    }
}

/// Constructor called when BoxLang evaluates `new rust:stats.RunningStats()`.
/// Allocates the object on the VM heap and returns a pointer value.
pub fn create_running_stats(vm: &mut dyn BxVM, _args: &[BxValue]) -> Result<BxValue, String> {
    let obj = RunningStats { values: Vec::new() };
    let id = vm.native_object_new(Rc::new(RefCell::new(obj)));
    Ok(BxValue::new_ptr(id))
}

// ---------------------------------------------------------------------------
// Registration — required entry points
// ---------------------------------------------------------------------------

/// Register standalone BIFs. MatchBox calls this at startup.
/// Register the `_wrapper` variants generated by `#[matchbox_fn]`.
pub fn register_bifs() -> HashMap<String, BxNativeFunction> {
    let mut map = HashMap::new();
    map.insert("fast_fib".to_string(), fast_fib_wrapper as BxNativeFunction);
    map.insert("fast_factorial".to_string(), fast_factorial_wrapper as BxNativeFunction);
    map
}

/// Register native object constructors. MatchBox calls this at startup.
/// Key format: "<module_filename>.<ClassName>" — this file is `stats.rs`,
/// so the key is `"stats.RunningStats"` and BoxLang uses
/// `new rust:stats.RunningStats()` to instantiate it.
pub fn register_classes() -> HashMap<String, BxNativeFunction> {
    let mut map = HashMap::new();
    map.insert("stats.RunningStats".to_string(), create_running_stats as BxNativeFunction);
    map
}
